export const trainingCategories = [
  { id: "shoot", name: "シュート", stats: ["finishing", "heading", "curl"] },
  { id: "pass", name: "パス", stats: ["lowPass", "loftedPass"] },
  { id: "dribble", name: "ドリブル", stats: ["ballControl", "dribbling", "tightPossession"] },
  { id: "defense", name: "ディフェンス", stats: ["defensiveAwareness", "ballWinning", "defensiveEngagement", "aggressiveness"] },
  { id: "quickness", name: "クイックネス", stats: ["acceleration", "bodyControl"] },
  { id: "strength", name: "足腰の強さ", stats: ["speed", "kickingPower", "stamina"] },
  { id: "aerial", name: "エアバトル", stats: ["heading", "jump", "physicalContact"] },
  { id: "gk1", name: "GK1", stats: ["goalkeeping", "catching"] },
  { id: "gk2", name: "GK2", stats: ["clearing", "collapsing"] },
  { id: "gk3", name: "GK3", stats: ["deflecting", "jump"] },
] as const;

export const statLabels: Record<string, string> = {
  offensiveAwareness: "オフェンスセンス",
  ballControl: "ボールコントロール",
  dribbling: "ドリブル",
  tightPossession: "ボールキープ",
  lowPass: "グラウンダーパス",
  loftedPass: "フライパス",
  finishing: "決定力",
  heading: "ヘディング",
  setPieceTaking: "プレースキック",
  curl: "カーブ",
  defensiveAwareness: "ディフェンスセンス",
  defensiveEngagement: "守備意識",
  ballWinning: "ボール奪取",
  aggressiveness: "アグレッシブネス",
  speed: "スピード",
  acceleration: "瞬発力",
  kickingPower: "キック力",
  jump: "ジャンプ",
  physicalContact: "フィジカルコンタクト",
  bodyControl: "ボディバランス",
  stamina: "スタミナ",
  goalkeeping: "GKセンス",
  catching: "キャッチング",
  clearing: "クリアリング",
  collapsing: "コラプシング",
  deflecting: "ディフレクティング",
};